version: 2

references:
  template: &template
    docker:
      - image: alpine
    steps:
      - run:
          name: test
          command: echo sinofseven

jobs:
  job_A:
    <<: *template
  job_B:
    <<: *template
  job_C:
    <<: *template
  job_D:
    <<: *template
  job_E:
    <<: *template
  job_F:
    <<: *template

workflows:
  version: 2
  test:
    jobs:
      - job_A
      - job_B:
          requires:
            - job_A
      - job_D:
          requires:
            - job_B
      - job_E:
          requires:
            - job_D
      - job_C
      - job_F:
          requires:
            - job_C