version: 2

jobs:
  parallel_test:
    parallelism: 2
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: execute parallel
          command: |
            set -x
            
            [[ "$CIRCLE_NODE_INDEX" == 0 ]] && make sleep-10 || make sleep-15


workflows:
  version: 2
  test:
    jobs:
      - parallel_test
